import { NoSsr } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import Navigation from './components/Navigation';
import './globals.css';
import Providers from './query';
import { themeInitScript } from './utils/themeInitScript';
const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <head>
        {/* Preventing FOUC by setting the font variables early */}
        <NoSsr>
          <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
        </NoSsr>
      </head>
      <body>
        <AppRouterCacheProvider>
          <Providers>
            <Navigation />
            <main className="container mx-auto p-4">{children}</main>
          </Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
