import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Navigation from './components/Navigation';
import './globals.css';
import Query from './query';
import { themeInitScript } from './utils/themeInitScript';
import { NoSsr } from '@mui/material';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preventing FOUC by setting the font variables early */}
        <NoSsr>
          <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
        </NoSsr>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Query>
          <Navigation />
          <main className="container mx-auto p-4">{children}</main>
        </Query>
      </body>
    </html>
  );
}
